# Generated by Django 4.1 on 2023-02-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_appointment', '0002_appointment_email_appointment_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
