# Generated by Django 4.1 on 2023-02-14 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_appointment', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comment_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
